export const UPDATE_VALUE = "UPDATE_VALUE";

export const TASK_LIST_FETCH_REQUESTED = "TASK_LIST_FETCH_REQUESTED";
export const TASK_LIST_FETCH_SUCCESSED = "TASK_LIST_FETCH_SUCCESSED";
export const TASK_LIST_FETCH_FAILED = "TASK_LIST_FETCH_FAILED";

export const TASK_SAVE_REQUESTED = "TASK_SAVE_REQUESTED";
export const TASK_SAVE_SUCCESSED = "TASK_SAVE_SUCCESSED";
export const TASK_SAVE_FAILED = "TASK_SAVE_FAILED";

export const TASK_DELETE_REQUESTED = "TASK_DELETE_REQUESTED";
export const TASK_DELETE_SUCCESSED = "TASK_DELETE_SUCCESSED";
export const TASK_DELETE_FAILED = "TASK_DELETE_FAILED";

export const TASK_CHANGE_STATUS_REQUESTED = "TASK_CHANGE_STATUS_REQUESTED";
export const TASK_CHANGE_STATUS_SUCCESSED = "TASK_CHANGE_STATUS_SUCCESSED";
export const TASK_CHANGE_STATUS_FAILED = "TASK_CHANGE_STATUS_FAILED";
